const PROJECTS = [
  {
    title: 'GlobalNomad',
    tag: 'Frontend Development',
    thumbnail: '',
    summary: '',
    duration: '',
    description: '',
    role: '',
    githubLink: '',
    demoLink: '',
  },
  {
    title: 'WekitBuket',
    tag: 'Frontend Development',
    thumbnail: '',
    summary: '',
    duration: '',
    description: '',
    role: '',
    githubLink: '',
    demoLink: '',
  },
  {
    title: 'Fandom-K',
    tag: 'Frontend Development',
    thumbnail: '',
    summary: '',
    duration: '',
    description: '',
    role: '',
    githubLink: '',
    demoLink: '',
  },
  {
    title: 'Feelkeen',
    tag: 'Web Publishing',
    thumbnail: '',
    summary: '',
    duration: '',
    description: '',
    role: '',
    githubLink: '',
    demoLink: '',
  },
  {
    title: '그라운드시소',
    tag: 'Web Publishing',
    thumbnail: '',
    summary: '',
    duration: '',
    description: '',
    role: '',
    githubLink: '',
    demoLink: '',
  },
  {
    title: '워클로',
    tag: 'Web Publishing',
    thumbnail: '',
    summary: '',
    duration: '',
    description: '',
    role: '',
    githubLink: '',
    demoLink: '',
  },
];

export default PROJECTS;
